<?xml version="1.0" standalone="yes"?>
<!DOCTYPE Simulation_Data[
<!ELEMENT Simulation_Data (LOCI,

InbreedingDepression,

Dioecious,Reproduction_Rate,
Offspring_Distribution,
SeedGerminationRate,
Pollen_Rate,Mortality_Rate,
SeedMortalityRate,
Selfing_Rate,RandomMating,
Agamospermy,
Dispersal_Distribution,
DispersalDirection,
EasyPollen,
PollenDirection,
Compatibility,
NewRegion,
SummaryRegions,
MakeMaps,
Immigration,
Number_Generations,Number_Runs,
DataInterval,
SeedCollection,
Initial_Population,CreateAllFounders,FoundersF)>
<!ELEMENT LOCI (locus)*>
<!ATTLIST LOCI number_loci CDATA #REQUIRED>
<!ATTLIST LOCI auto_alleles_per_locus CDATA #IMPLIED>
<!ATTLIST LOCI number_automatic_loci CDATA #IMPLIED>


<!-- 29 June 2014 InbreedingDepression-->
<!ELEMENT InbreedingDepression (IBD_ReproductionEffect,IBD_MortalityEffect)>
<!ATTLIST InbreedingDepression
    use (true|false) #REQUIRED
    depressionloci CDATA #REQUIRED
    depression_reproduction (true|false) #REQUIRED
    depression_mortality (true|false) #REQUIRED>
<!ELEMENT IBD_ReproductionEffect EMPTY>
<!ATTLIST IBD_ReproductionEffect
    x CDATA #REQUIRED
    y CDATA #REQUIRED>

<!ELEMENT IBD_MortalityEffect EMPTY>
<!ATTLIST IBD_MortalityEffect 
    x CDATA #REQUIRED
    y CDATA #REQUIRED
    f CDATA #REQUIRED>
    
 <!-- 29 June 2014 InbreedingDepression-->   
<!ELEMENT Dioecious EMPTY>
<!ATTLIST  Dioecious value (true|false) #REQUIRED>
<!ELEMENT locus  (dpdpoint)*>
<!ATTLIST locus
    action (compatibility|dispersal|fitness|inbreeding) #IMPLIED>
    
<!ELEMENT dpdpoint EMPTY>
<!ATTLIST dpdpoint
    x CDATA #REQUIRED
    y CDATA #REQUIRED>
<!ELEMENT functionpoint EMPTY>
<!ATTLIST functionpoint
    x CDATA #REQUIRED
    y CDATA #REQUIRED>
<!ELEMENT Reproduction_Rate (functionpoint)*>



<!ELEMENT Offspring_Distribution EMPTY>
<!ATTLIST Offspring_Distribution 
    method (round|bracket|poisson) #REQUIRED>
    
<!ELEMENT SeedGerminationRate (functionpoint)*>



<!ELEMENT SeedMortalityRate (functionpoint)*>
    
    
<!ELEMENT Pollen_Rate (functionpoint)*>
<!ELEMENT Mortality_Rate (functionpoint)*>
<!ELEMENT Selfing_Rate EMPTY>
<!ATTLIST Selfing_Rate value CDATA #REQUIRED>
<!ELEMENT RandomMating EMPTY>
<!ATTLIST RandomMating value CDATA #REQUIRED>

<!ELEMENT Agamospermy EMPTY>
<!ATTLIST Agamospermy
    use (true|false) #REQUIRED
    method (all|facultative) #REQUIRED
    probability CDATA #REQUIRED>
<!--
<!ELEMENT Fruit_Distance EMPTY>
<!ATTLIST Fruit_Distance value CDATA #REQUIRED>
-->
<!ELEMENT Dispersal_Distribution (functionpoint)*>
<!ELEMENT DispersalDirection (functionpoint)*>
<!ATTLIST DispersalDirection
    use (true|false) #REQUIRED>
    
<!ELEMENT EasyPollen (pollenframe)*>
<!ELEMENT pollenframe EMPTY>
<!ATTLIST pollenframe
      low CDATA #REQUIRED
      high CDATA #REQUIRED
      prob CDATA #REQUIRED>

<!ELEMENT PollenDirection (functionpoint)*>
<!ATTLIST PollenDirection
    use (true|false) #REQUIRED>
    
<!ELEMENT Compatibility EMPTY>
<!ATTLIST Compatibility
    value CDATA #REQUIRED
    compatibility_fraction CDATA #REQUIRED
    locus CDATA #REQUIRED>
    
    <!--22june14 revert to earlier Region
<!ELEMENT Region (Rectangle|SparseRectangle|ConvexPolygon|DynamicRect)*>
-->
<!ELEMENT Region (Rectangle|ConvexPolygon)*>
<!ATTLIST Region
    XL CDATA #REQUIRED
    YL CDATA #REQUIRED
    XH CDATA #REQUIRED
    YH CDATA #REQUIRED>
    
<!ELEMENT NewRegion (NewRectangle)*>
    <!ATTLIST NewRegion
    XL CDATA #REQUIRED
    YL CDATA #REQUIRED
    XH CDATA #REQUIRED
    YH CDATA #REQUIRED>
  
    <!--  
<!ELEMENT regionpoint EMPTY>
<!ATTLIST regionpoint
    a CDATA #REQUIRED
    b CDATA #REQUIRED>
    -->
    
 <!ELEMENT NewRectangle (ClustersPerYear*,SitesPerCluster*,SiteLifetime*)>
  <!ATTLIST NewRectangle
    XL CDATA #REQUIRED
    YL CDATA #REQUIRED
    XH CDATA #REQUIRED
    YH CDATA #REQUIRED
    type (PLAIN|RANDOM|DYNAMIC) #REQUIRED
    density CDATA #IMPLIED
    name CDATA #IMPLIED>
    
<!ELEMENT Rectangle EMPTY>
<!ATTLIST Rectangle
    XL CDATA #REQUIRED
    YL CDATA #REQUIRED
    XH CDATA #REQUIRED
    YH CDATA #REQUIRED
    name CDATA #IMPLIED>
   


<!ELEMENT ConvexPolygon (Vertex)*>
<!ELEMENT Vertex EMPTY>
<!ATTLIST Vertex
    x CDATA #REQUIRED
    y CDATA #REQUIRED>
    
  
  <!ELEMENT ClustersPerYear (functionpoint)*>
 <!ATTLIST ClustersPerYear
   distribution (poisson|uniform|constant|cdf) #IMPLIED
   value CDATA #IMPLIED
   mean CDATA #IMPLIED
   min CDATA #IMPLIED
   max CDATA #IMPLIED>
   
   <!ELEMENT SitesPerCluster (functionpoint)*>
  <!ATTLIST SitesPerCluster
   distribution (poisson|uniform|constant|cdf) #IMPLIED
   value CDATA #IMPLIED
   mean CDATA #IMPLIED
   min CDATA #IMPLIED
   max CDATA #IMPLIED>
  <!ELEMENT SiteLifetime (functionpoint)*>
  <!ATTLIST SiteLifetime
   distribution (poisson|uniform|constant|cdf) #IMPLIED
   value CDATA #IMPLIED
   mean CDATA #IMPLIED
   min CDATA #IMPLIED
   max CDATA #IMPLIED>
  
   
   

 <!ELEMENT SummaryRegions (Region)*>
 


<!ELEMENT MakeMaps (Vector)>
<!ATTLIST MakeMaps 
use (true|false) #REQUIRED
pixelsPerSite CDATA #IMPLIED
>

 <!ELEMENT Immigration (Vector)*>
 <!ATTLIST Immigration use (true|false) #REQUIRED
rate CDATA #REQUIRED
pfemale CDATA #REQUIRED
>

 <!ELEMENT Vector EMPTY>
 <!ATTLIST Vector 
 name CDATA #REQUIRED
 length CDATA #REQUIRED
 values CDATA #REQUIRED>
<!ELEMENT Number_Generations EMPTY>
<!ATTLIST Number_Generations value CDATA #REQUIRED>
<!ELEMENT Number_Runs EMPTY>
<!ATTLIST Number_Runs value CDATA #REQUIRED>
<!ELEMENT DataInterval EMPTY>
<!ATTLIST DataInterval value CDATA #REQUIRED>

<!ELEMENT SeedCollection EMPTY>
<!ATTLIST SeedCollection
    use (true|false) #REQUIRED
    subregions_only (true|false) #REQUIRED
    seed_dump_file_name CDATA #REQUIRED
    last_r CDATA #REQUIRED>
    
<!ELEMENT Plant EMPTY>
<!ATTLIST Plant
    age CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    femaleP (true|false) #REQUIRED>
<!ELEMENT age EMPTY>
<!ATTLIST age value CDATA #REQUIRED>
<!ELEMENT femaleP EMPTY>
<!ATTLIST femaleP value (true|false) #REQUIRED>

<!ELEMENT location EMPTY>
<!ATTLIST location
    X CDATA #REQUIRED
    Y CDATA #REQUIRED>
    <!ELEMENT RandomPlantList EMPTY>
<!ATTLIST RandomPlantList
    number CDATA #REQUIRED
    numberfemale  CDATA #REQUIRED
    XL  CDATA #REQUIRED
    YL CDATA #REQUIRED
    XH CDATA #REQUIRED
    YH CDATA #REQUIRED
    probfemale  CDATA #REQUIRED
    agelow  CDATA #REQUIRED
    agehi  CDATA #REQUIRED>
<!ELEMENT Initial_Population (Plant|RandomPlantList)*>
<!ELEMENT CreateAllFounders EMPTY>
<!ATTLIST CreateAllFounders value (true|false) #REQUIRED>
<!ELEMENT FoundersF EMPTY>
<!ATTLIST FoundersF value CDATA #REQUIRED>
]>

<!--
Use this file (or copies of it that you modify) to control the values
 of the parameters of the model.
 
You need to give the name of such a parameter file on the command line every time you
run the NEWGARDEN program. 

This file is to work with/test out/document



X NewGarden version 2.73 (30 June 2014)
X NewGarden version 2.74 (7 July 2014)
-> NewGarden version 2.75 (7 Sept 2014)
NOTE older SimData.xml files may not work with this version of NEWGARDEN.
and older versions of NewGarden may not work with this format of parameter file.



It includes  2012 improvements; and 2013 improvements especially 
1) the revised implementation of a SEEDBANK 
2) provision for IMMIGRATION from the founding population 
3) SPARSE Rectangles (that miss a certain fraction of their grid points)
4) A COMPATIBILITY SYSTEM (Nov 2013)
5) DynamicRect s in which viable sites appear and diasapper Dec 2013
6) NewRegion and New Rect now used for describing regions but not for summary regions (which are not dynamic)
7) Can now specify years in run 0 for which maps are drawn
8) DisperalDirection and PollenDirection can now be selected at random
    according to user specified distributions. But you can turn this feature off.
9( You can request that maps be drawn showing the distribution of viable sites, plants, and seeds
    during selected years during the first run of the simulation.
10) 20 May 2014 Now contains a SeedCollection program for post-processing data dumped at the end of
a regular NewGarden run, and a new XML element in SimData that turns this data dumping on and off.
11) 8 June 2014 Returned to old version for treating RandomPlantLists where we aggregate all requests
    for founders in a given rectangle (Different ages or sexes, perhaps) and get locations for
    them all at once so that there are never two at one location.
12) NewRectangles now have an optional attribute called name. This can be used to
   document their purpose. Eventually RandomPlantLists can be placed in named NewRectangles
   so that we can find locations for founders even in RANDOM or DYNAMIC rectangles
13) Can now specify pixelsPerSite that gets handed on to Image when making maps. Potentially useful
for Emma's project about making a movie. TODO: allow a color scheme with darker greens for older plants

14) 7 July 2014 Inbreeding Depression is now implemented (changes to Plant, SimData, SimDataReader,Model) We calculate the actual excess homozygosity (relative to FoundersF)
and use this to (optionally)  alter ReproductionRate by a user defined factor or alter mortality calculating it according to a user defined function of excesshomozygosity and age.

7July2014 bug fix in SeedCollection subscript out of bounds in NearestNeighbor section because RandomInteger may have equaled collation.size().

15) Sept 2014 Changed the seed collection program to also calculate pathlengths, and do it
    by subrectangles if the SUmmary region isn't just 1 rectangle.
    
This new version also makes some older SimData parameter files unacceptable.
For example, now we only allow EasyPollen as a way of specifying pollen distribution;
the two older methods are no longer supported

OPTIONS FOR STATISTICS AND REDUCTION OF MEMORY REQUIREMENTS

1. You can use the "skipstats" commandline option. Then the entire population
is dumped to a text file for later processing by the ReadData program.

2. You can use the "smallstats" commandline option. This causes the program to store
intermediate statistics in a file on disk, read them in at the end and produce output
as usual.

3. Don't use either of those options and the program will work the way it always has.

The option of using "skipstats" and dumping data to an output file can result in a huge
output file. A run of 80 generations with 80 replicates produced a dump file of 560MB!!


-->

<Simulation_Data>
    <!-- LOCI
    Specify the number of loci to simulate,
    the number of alleles at each locus and 
    the frequency of alleles at each locus

    The attributes auto_alleles_per_locus and
    number_automatic_loci are optional and provide a shorthand
    for generating multiple loci with the same number of alleles and
    same allele frequencies.

    Otherwise, simply include one <locus>...</locus> element
    for each locus to be simulated.

    THIS IS A CHANGE FROM EARLIER VERSIONS:
    The required attribute number_loci should equal the number of <locus>...</locus>
    elements used to specify loci; it DOES NOW include the number of
    automatically generated loci.

    The <dpdpoint>...</dpdpoint> elements in the <locus>...</locus> elements
    each create an allele at that locus. The x attribute is the frequence of
    the allele and the y attribute is the label (name) of the allele.

    The LOCI element below specifies a simulation with 7 loci. One locus 
    has 3 alleles with frequencies 0.25,0.25,0.5; one has 2 alleles with 
    frequencies 0.05 and 0.95. The remaining 5 loci each have 2 equally 
    probable alleles.
    <LOCI number_loci="1" auto_alleles_per_locus="2" number_automatic_loci="1">
    
    locus has an attribute called 'action' that is ignored by the program (currently dec 2013)
    but serves as documentation and can later be used as a check on the consistency
    or the parameter specifications
    
    FEB 2014 number_loci is now the total number of loci auto generated and individually
    specified.
    
    June 29 2014 Introduce InbreedingDepression and arrange for SimData to contain the necessary variable,
    to output them when writing XML, and for SimDataReader to parse the XML elements
    and initialize them for SimData.
   -->
    <LOCI number_loci="14" number_automatic_loci="10" auto_alleles_per_locus="20">
        <!-- the first locus listed explicitly is the compatibility locus and
        stored as locus number 0 in the array of loci if there are no auto loci
        it is stored at number_automatic_loci if there are auto generated loci-->
        <!-- the thing described here is locus number 10 
        The action attribute is optional but possibly useful for documenting what the
        file intends. It may be checked in the future to ensure that the 
        compatibility locus is labeled
        with this action attribute value.
        
        Starting 29 June 2014 we'll also allow alleles to be considered to calculate homozygosity
        and use this to reduce reproduction or increase mortality.-->
        <locus action="compatibility">
            <dpdpoint x="0.25" y="0"/>
            <dpdpoint x="0.25" y="1"/>
            <dpdpoint x="0.25" y="2"/>
            <dpdpoint x="0.25" y="3"/>
        </locus>
        <!-- the next 3 loci are to be used in estimating inbreeding
        they are loci number 11-13-->
           <locus action="inbreeding">
            <dpdpoint x="0.25" y="0"/>
            <dpdpoint x="0.25" y="1"/>
            <dpdpoint x="0.25" y="2"/>
            <dpdpoint x="0.25" y="3"/>
        </locus>  
        
        <locus action="inbreeding">
            <dpdpoint x="0.25" y="0"/>
            <dpdpoint x="0.25" y="1"/>
            <dpdpoint x="0.25" y="2"/>
            <dpdpoint x="0.25" y="3"/>
        </locus>  
        <locus action="inbreeding">
            <dpdpoint x="0.25" y="0"/>
            <dpdpoint x="0.25" y="1"/>
            <dpdpoint x="0.25" y="2"/>
            <dpdpoint x="0.25" y="3"/>
        </locus>  
        
    </LOCI>
    
    
    <!-- InbreedingDepression 30 June 2014
    
    This element controls how the homozygosity of a plant in excess of that
    expected for the Founders alters the age-dependent reproduction rate
    and/or age dependent mortality rate.
    
    use  is true/false and turns on the operation of this stuff
    depressionloci is a list of loci to be used in computing 
        the homozygosity of a plant and the expected homozygosity of founders
        You can only refer to loci that exist (not bigger then number_loci-1
    depression_reproduction  and
    depression_mortality are true/false
    and determine whether excess homozygosity is used to alter r and/or m
    
    
    -->
    <InbreedingDepression 
    use="true"
    depressionloci="10,11,12,13"
    depression_reproduction="true"
    depression_mortality="true"
    >
    <!-- ReproductionEffect is a multiplier giving the factor to reduce the
    age-dependent reproduction rate by based on excess homozygosity
        So when excess homozygosity is 0, the multiplier would
        typically be 1, and these values might well decrease with increasing
        excess homozygosity
       
        -->
    <IBD_ReproductionEffect x="0,0.5,1" y="1,0.8,0.5"/>
    
   

<!-- the first variable is excesshomozygosity, and second variable is age
    for x=0 this should just be the normal age dependent mortality rate
     x="0,1,4,7,10"
     y="0,1"
     f="0,0.2,0.5,0.5,1,0.3,0.5,0.6,0.6,1"
    
    -->
    
  <!--  <IBD_MortalityEffect x="0,1" y="0,1"  f="0,0.5,0.75,1"/>-->
 
    <IBD_MortalityEffect y="0,1,4,7,10"
     x="0,1"
     f="0,0.2,0.5,0.5,1,0.3,0.5,0.6,0.6,1"/>
    
    
</InbreedingDepression>

    <!-- Dioecious
    Is the population di- or mono-?
    You can set the required attribute to be "true" or "false"
    -->
    <Dioecious value="false"/>
    
    <!-- Reproduction_Rate
     Potential offspring generated per breeding cycle
     as a function of age of female parent.

    Actually this gives the expected number of offspring that are generated
    and have a chance to be established

    The way in which this data is used in the simulation is user-specified. You can
     use the the parameters below to specify the exact number of potential offspring 
    each parent generates or you can use the paramters to specify the mean number generated. 
    In this case the number of offspring per parent of will be chosen at random from a 
    Poisson distribution.

     In the functionpoint elements below the attribute "x" is the age and the attribute "y" is
    the number of offspring. These function point elements represent points on the graph giving the
     age dependence of offspring number vs. age of parent. The value of y at an x not explicitly specified
     is determined by linear interpolation.

      The specific example below describes high reproduction at early ages with reproduction declining to
      0 at age 8 and higher.
    -->
    <Reproduction_Rate>
        <functionpoint x="0" y="4"/>
        <functionpoint x="1" y="4"/>
        <functionpoint x="2" y="4"/>
        <functionpoint x="7" y="1"/>
        <functionpoint x="8" y="0"/>
        <functionpoint x="10" y="0"/>
        <functionpoint x="11" y="0"/>
        <functionpoint x="20" y="0"/>
    </Reproduction_Rate>

    <!--Offspring_Distribution
    This controls how the"fruit production vs age distribution" is implemented.

    This element has one attribute called method. You can assign it one of the values
    "bracket","poisson",and "round". If you don't specify one of these the default
    behavior is "round"

    "poisson" results in the simulation picking a possion random number with
    the specified mean when deciding how many offspring to generate for each parent.

    "round" simply rounds the specified number down to the nearest whole number.

    "bracket" chooses between rounding down and rounding up to the nearest
    whole numbers so that the average is that specified by the age distribution.
    -->
    <Offspring_Distribution method="bracket"/>

<!--SeedProductionRate controls the age-dependent contribution
made each round of breeding to the seedbank

This distribution determines the number of seeds we try to generate
to donate to the bank. Failed pollination resutls in a smaller
number of seeds donated, as does having seed's randomly
selected location fall outside the Region.

It works that same wasy as Reproduction_Rate

Just as with Reproduction_Rate you can also choose the distribution
of the number produced.

If you set this function to be always 0 the program
won't waste much time, This is essentially how one turns off
the seedbank option

TO eliminate the seedbank make all seeds germinate immediately
    by doing this:

<SeedGerminationRate>
    
    <functionpoint x="0" y="1.0"/>
    <functionpoint x="1" y="0"/>
</SeedGerminationRate>
-->
<SeedGerminationRate>
    
    <functionpoint x="0" y="0.9"/>
    <functionpoint x="2" y="0.4"/>
    <functionpoint x="8" y="0.1"/>
</SeedGerminationRate>


    <!-- Pollen_Rate
    The relative chance of donating pollen as a function of age.

    The <functionpoint>...</functionpoint> elements specify
    pollen rate (y) at different ages (x).

    These points are interpolated linearly to get values for other (intermediate) ages.

    In this example the relative chance of donating pollen is independent of age.
    -->
    <Pollen_Rate>
        <functionpoint x="0" y="1"/>
        <functionpoint x="1" y="1"/>
        <functionpoint x="2" y="1"/>
        <functionpoint x="7" y="1"/>
        <functionpoint x="8" y="1"/>
        <functionpoint x="10" y="1"/>
        <functionpoint x="11" y="1"/>
        <functionpoint x="20" y="1"/>
    </Pollen_Rate>
    
    <!-- Mortality_Rate
    Chance of dying during previous "year" as a function of age

    More techincally, this is the age dependent chance of dying 
    immediately after the  indicated generation (= population age)
    bout of reproduction  
  
    The <functionpoint>...</functionpoint> elements specify
    points on the graph of mortality rate vs. age. (x is age, y is 
    mortality rate)
    
    These points are interpolated linearly to get values for ages not
    exlicitly specified.

    In the example below there's no mortaility in the first years and
    everything is dead by age 10.
    -->
    <Mortality_Rate>
        <functionpoint x="0"  y="0"/>
        <functionpoint x="1"  y="0.2"/>
        <functionpoint x="4"  y="0.5"/>
        <functionpoint x="7"  y="0.5"/>
        <functionpoint x="10" y="1"/>
        <functionpoint x="11" y="1"/>
        <functionpoint x="20" y="1"/>
    </Mortality_Rate>
    
    <!--SeedMortalityRate controls death of seeds
    in the seedbank in an age dependent way.
    
    It works just like Mortality_Rate
    
    TO eliminate the seedbank, do this
     <SeedMortalityRate>
        <functionpoint x="0"  y="1"/>
        <functionpoint x="1"  y="1"/>
    </SeedMortalityRate>
    
    -->
    <SeedMortalityRate>
        <functionpoint x="0"  y="0"/>
        <functionpoint x="1"  y="0.2"/>
        <functionpoint x="4"  y="0.5"/>
        <functionpoint x="7"  y="0.5"/>
        <functionpoint x="10" y="1"/>
    </SeedMortalityRate>
    <!-- Selfing_Rate
    selfing rate for monoecious population
    
    There is one required attribute named value that 
    should be assign a decimal between 0.0 and 1.0 inclusive.
    -->
    <Selfing_Rate value="0.0"/>
    
    <!-- RandomMating
    What to do if selfing=0

    Do we allow some self crosses even if selfing is 0 
    so that mating is random (true) or exclude them (false)?
    
    True random mating implies that all possible matings are equally likely 
    and this includes self-matings. If the parameter selfing is set to 0 
    (or any other specific value) the matings simulated by the program will not 
    be truely random since selfing occurs at a fixed, user-specified rate.

    The required attribute called value is either "true" or "false"
    
    This determines whether  random mating (including selfings) is 
    simulated (if "true") or not (if "false") in the situations
    where Selfing_Rate is specified as "0.0". 
    -->
    <RandomMating value="false"/>
    
    
    <!-- 18 May 2014

    <Agamospermy ../> lets us specify whether and how to include it in
    the reproduction part of the model
    
    attribute use is eitehr true - we do allow agamospermy
    or false - we don't and program runs as before
   
   attribute method is either all or facultative
   
   with method="all" a certain fraction of all reproductions are by apomixis
   with method="facultative" a certain fracntion of pollinations that
   fail due to lack if pollen source are by apomixis
   
   attribute probability os a float between 0 and 1 and gives that
   chance, on a give try, that reproduction by apomixis proceeds. Otherwise
   no potential offspring are produced.
   -->
    <Agamospermy use="true" method="facultative" probability="0.4"/>
    <!-- Dispersal_Distribution
    describes the probability that an offspring moves to occupy a grid
    point at distance d from maternal parent.

    The first point in this element needs to be

    <functionpoint x="0" y="0"/>

    so that only non-negative distances are selected.

    The distribution of disperal distances is given
    as a Cumulative Distribution so adding the point

    <functionpoint x="12" y="0.5"/>

    says that the probability that the randomly chosen dispersal distance is
    <= 12 is 50%. This means that with probability 50% one of the values 0,1,....,11,12
    will occur. 

    To make the chance of dispersing exactly
    12 units equal to 0.1, the next entry should be

    <functionpoint x="13" y="0.6"/>

    Since then the chance that the distance is between 12 and 13 is 0.6-0.5 =0.1

    Our distances are always whole numbers and WE ROUND DOWN HERE

    If the maximum distance possible is to be D the last functionpoint should be

    <functionpoint x="D+1" y="1.0"/>

    since then some number between 0 and D is always selected
    -->
    <Dispersal_Distribution>
        <functionpoint x="0" y="0"/>
        <functionpoint x="1" y="0.05"/>
        <functionpoint x="2" y="0.1"/>
        <functionpoint x="3" y="0.49"/>
        <functionpoint x="6" y="1.0"/>
    </Dispersal_Distribution>
   
   <!-- DispersalDirection is a CDF that lets us choose a random direction
   MARCH 6 2014
   This gives a cumulative distribution of angles (measured in degrees
 from 0=due north to 360 moving clockwise) it is used for picking a random direction
 in which an offspring disperses from its parent. The site closest to this direction
 and at the distance determinded by Dispersal_Distrbution is the one slected.
 
  If you set the attribute use to "false" then the program calculates dispersal
  by the original method in which each site at the specified distance is equally likely
   
   -->
    <DispersalDirection use="true">
        <functionpoint x="0" y="0"/>
        <functionpoint x="360" y="1"/>
    </DispersalDirection>
    <!--EasyPollen 

   For each mating the realtive chances that a plant is a pollen donor
depend on the age of the plant and its distance from the maternal parent.
The age dependence is given by the Pollen_Rate element.

EasyPollen describes the distance dependence.
   It  provides a means for specifying the chance that a pollen
    source is at different distances from a female parent.
    
    
    Different distance frames (or bands or rings)  are specified with <pollenframe/> elements.
    These elements give the upper and lower limits of the distances for
    each frame  and the probability that the distance to a pollen source 
    lies between the values low and high specified in the <pollenframe/>
    statement.
    
    In this example when a pollen source is selected for any mating there will be a 
    50% chance that it is at a distance between 0 and 2 from a maternal
    parent and 5% that it is at a 
    distance of 7 or more; the remaining time the distance will be between
    3 and 6 inclusive.

    Technically, you want to ensure that the probabilities are non negative and add up to 1.
    -->
    <EasyPollen>
        <pollenframe low="0" high ="2" prob="0.5"/>
        <pollenframe low="3" high ="6" prob="0.45"/>
        <pollenframe low="7" high ="Inf" prob="0.05"/>
    </EasyPollen>
    
    
    <!-- MARCH 2014
    PollenDirection gives the probability, based on direction (angle) FROM maternal partent,
    that a potential pollen source is included in the lottery to contribute pollen
    
    if the attribute use is "false" pollenator selection ignores direction and is
    carried out by the old (original) method
    
    Shown here is a mildly strong west wind plants upwind 270 degrees from parent
    are sure to be conisdered as pollen sources, those downwind (90 degrees) have a 25% chance.
    
    -->
    <PollenDirection use="true">
        <functionpoint x="0" y="0.5"/>
        <functionpoint x="90" y="0.25"/>
        <functionpoint x="180" y="0.5"/>
        <functionpoint x="270" y="1"/>
        <functionpoint x="360" y="0.5"/>
    </PollenDirection>
    <!-- Compatibility uses one locus as a compatibiity system. Fertilization is achived as usual
    except that compatibility_fraction of the time we don't generate a potential offspring if
    the pollen has a locus 1 allele that is one of the two in the maternal parent.
    This "failure" counts as one of the potential founders generated in a given year for a particular maternal plant.
    
    So compatibility_fraction is the "strength" of the compatibility system.
    The sysem prevents polination/fertiliation compatibility_faction of the time
    that this is called for by the genotypes involved.
    
    Setting value to false turns off consideration of the system and compatibility_fraction is ignored and has no effect.
    If value is true and compatibility_fraction is 0, again there is no effect but the model spends time
    checking genotypes.
    
    The attribute locus gives the number of the locus to use as the compatibility locus.
    If there's no aut-generated loci, the first locus specified in the LOCI element
    is number 0.
    
    If N auto loci are specified, then N is the number of the locus specified by
    the first locus element in the LOCI element.
    Dec 14 2013 
    
    31 Jan 2014 now that the action attribute for Locus is available
    we could/should check that locus of the number specified here
    is actually action.equals("compatibility");
    -->
    
    <Compatibility value="true" compatibility_fraction="1.0" locus="10"/>
   

    <!--Region
    The region is specified by giving the coordinates of lower left
    and upper right vertices of a rectangle. If you only want everything
    to take place in one big rectangle, you can give the Region statement
    without any Rectangle subelements.

    <Region XL="0" XH="70" YH="70" YL="0"/>